### ISSUE TITLE
Request: disable this message: "Auto run command is working..."

### ISSUE THREAD

**Issue by hepiyellow** [GabiGrin/vscode-auto-run-command#22]
This message is really annoying:
`Auto run command is working. Checkout the README to make it do something useful!` 

I would remove it.

As a workaround I added this in my User's settings:
```
"auto-run-command.rules": [
        {
            "condition": "hasFile: a-file-name-which-should-never-exists",
            "command": "auto-run-command.placeholder-command",
            "message": "Running a dummy command"
        }
    ]
```

And I add the auto-run config for wallaby only in the projects that need it.

It would be nicer if `condition` could be `never`.

**Comment by GabiGrin** [comment]
You can just set the rules array to be empty
```
"auto-run-command.rules": [
    ]
```

**Comment by hepiyellow** [comment]
That's a nicer workaround, but still a workaround.

I don't think the this message should be default behavior.

This means that anyone who installs this extension, should also manually modify their user-settings.

**Comment by ranyitz** [comment]
Yes, I agree that there are some codebases where we need `auto-run-command` and there are some codebases that we don't. Having this message everytime you open vscode can make some people to uninstall the extension.

I also understand why @GabiGrin as an extension maintainer would like to notify the users on the first usage that they need to configure something in order to make it work.

Maybe it should show up only on the first time?
